version: '3.8'
services:
  postgres:
    image: ghcr.io/orion6dev/pg-german:fix-1
    command: postgres -c 'max_connections=2000'
    container_name: postgres
    pull_policy: always
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test*12*
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_SCHEMA=public
      - POSTGRES_SSLMODE=Disable
    volumes:
      - postgresql_etc:/etc/postgresql
      - postgresql_log:/var/log/postgresql
      - postgresql_lib:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: test@feuerfest.dev
      PGADMIN_DEFAULT_PASSWORD: test*12*
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:
    driver: local
    driver_opts:
      type: none
      device: ${USERDIR}/pgadmin
      o: bind
  postgresql_etc:
    driver: local
    driver_opts:
      type: none
      device: ${USERDIR}/postgresql/etc
      o: bind
  postgresql_log:
    driver: local
    driver_opts:
      type: none
      device: ${USERDIR}/postgresql/log
      o: bind
  postgresql_lib:
    driver: local
    driver_opts:
      type: none
      device: ${USERDIR}/postgresql/lib
      o: bind
