services:
  postgres:
    # Using a custom PostgreSQL image tailored for German-specific setups.
    image: ghcr.io/orion6dev/pg-german:local
    container_name: postgres
    restart: on-failure
    # Healthcheck to ensure the database is ready to accept connections.
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    # Mapping the PostgreSQL default port 5432 on the host to the container.
    ports:
      - "5432:5432"
    # Environment variables to configure the PostgreSQL instance.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test*12*
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_SCHEMA=public
      - POSTGRES_SSLMODE=Disable
    # Volumes for persistent storage and configuration management.
    volumes:
      - postgresql-etc:/etc/postgresql
      - postgresql-log:/var/log/postgresql
      - postgresql-lib:/var/lib/postgresql
      - postgresql-data:/var/lib/postgresql/data  # Explicitly manage the PGDATA directory 
      - ./test-ssh/postgres/:/home/postgres/.ssh/
    # Command to start PostgreSQL and set permissions for SSH files
    command: /bin/sh -c "\
      chown -R postgres:postgres /home/postgres/.ssh && \
      chmod 700 /home/postgres/.ssh && \
      chmod 600 /home/postgres/.ssh/authorized_keys && \
      chmod 600 /home/postgres/.ssh/config && \
      chmod 600 /home/postgres/.ssh/id_ed25519_test && \
      chmod 644 /home/postgres/.ssh/id_ed25519_test.pub && \
      postgres -c config_file=/etc/postgresql/postgresql.conf"
    
  pgadmin:
    # PgAdmin 4: A web-based administration tool for PostgreSQL.
    # More info: https://www.pgadmin.org/
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: on-failure
    # Ensuring pgadmin starts only after postgres is available.
    depends_on:
      - postgres
    # Configuration through environment variables.
    environment:
      PGADMIN_DEFAULT_EMAIL: test@feuerfest.dev
      PGADMIN_DEFAULT_PASSWORD: test*12*
    # Persistent volume for pgadmin configurations and sessions.
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  network-multitool:
    image: wbitt/network-multitool:extra
    container_name: network-multitool
    volumes:
      - ./test-ssh/postgres/:/home/root/.ssh/
    user: "root:root"
    command: /bin/sh -c "\
      chown -R root:root /usr/share/nginx/html && \
      chown -R root:root /var/lib/nginx/logs && \
      chown -R root:root /home/root/.ssh && \
      chmod 700 /home/root/.ssh && \
      chmod 600 /home/root/.ssh/authorized_keys && \
      chmod 600 /home/root/.ssh/config && \
      chmod 600 /home/root/.ssh/id_ed25519_test && \
      chmod 644 /home/root/.ssh/id_ed25519_test.pub && \
      nginx -g 'daemon off;'"
volumes:
  # Local driver is used for all volumes for simplicity and local development purposes.
  pgadmin-data:
    driver: local
  postgresql-etc:
    driver: local
  postgresql-log:
    driver: local
  postgresql-lib:
    driver: local
  postgresql-data:
    driver: local  
  pgbackrest-backup:
    driver: local  
